### ISSUE TITLE
Replace Coffeescript?

### ISSUE THREAD

**Issue by justin** [tree-sitter/tree-sitter-swift#13]
I don't want to go down this road unless its approved, but any reason to not mimic the other more active tree-sitter libraries and just use plain old JavaScript?

**Comment by robrix** [comment]
No reason I can think of. I’d welcome the change tbh!

**Comment by justin** [comment]
On it. 

hoping to get Atom + Swift to be better friends so I can stop fighting Xcode Playgrounds. :)
