### ISSUE TITLE
Consider joining forces with `experimental-tree-sitter-swift`?

### ISSUE THREAD

**Issue by alex-pinkus** [tree-sitter/tree-sitter-swift#37]
Back when the licensing for this repository seemed unclear, I started an alternative grammar here that was intentionally not based on this one:

https://github.com/alex-pinkus/experimental-tree-sitter-swift

That grammar has a pretty good parse rate now, and supports some features this one doesn't yet (like #24, #27, #28, #32). What do you think it would take to unify the two efforts?

**Comment by maxbrunsfeld** [comment]
I added a link to your grammar in the README, and a note that this is unmaintained. I think you should go ahead and drop the `experimental` part from the name of yours, and I'll add a link to it from Tree-sitter's docs site as well. Then at some point, I'll archive this repo.

**Comment by alex-pinkus** [comment]
Thank you @maxbrunsfeld for adding the link! I just renamed `alex-pinkus/experimental-tree-sitter-swift` to `alex-pinkus/tree-sitter-swift`. I appreciate the encouragement!

**Comment by rewinfrey** [comment]
👋 @maxbrunsfeld @alex-pinkus from one of the folks working on parsing, highlighting, and search related features at GitHub. We're in the process of updating our highlighting service to use `alex-pinkus/tree-sitter-swift`, and it caused us to pause and ask "would it be possible to have `alex-pinkus/tree-sitter-swift` become `tree-sitter/tree-sitter-swift`? I realize this is a series of steps that requires time / effort, and is likely the last thing on anyone's radar, but would like to gauge interest in that outcome to see if either of you would be interested in that.

All the above aside, thank you @alex-pinkus for owning and maintaining `tree-sitter-swift`, and we're excited to incorporate it into our syntax highlighting service to improve Swift syntax highlighting for files on GitHub. 🙇‍♂ ❤

**Comment by alex-pinkus** [comment]
Thanks, @rewinfrey -- appreciate the kind words!

Heads up that I've just updated the grammar to add support for a few newer Swift language features. There might be more updates incoming if I can find the time for them.

Asking just to understand: would re-homing the grammar under the `tree-sitter` org have practical implications for GitHub language support, or is it simply a question of optics? I'm not opposed to handing it over if they want it (as long as I retain edit permissions), but I'm just curious whether there'd be a technical reason to do so.
